apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dynamic-kingfisher-python
  janus-idp.io/tekton: dynamic-kingfisher-python
  backstage.io/kubernetes-id: dynamic-kingfisher-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dynamic-kingfisher-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
